### ISSUE TITLE
Group by not working with ajaxfied lists

### ISSUE THREAD

**Issue by trob** [Fabrik/fabrik#1528]
TypeError: d.each is not a function
http://localhost/j33/media/com_fabrik/js/list.js
Line 821

**Comment by trob** [comment]
Can't see the JS error any longer, but very strange effects:
Group by is not grouping but sorting.

If no. of rows is changed it's showing "no data".

Even if no. of rows is set to 50 before "group by" it's reset to 10 after (not grouping but sorting) group by.

**Comment by trob** [comment]
Still in 3.4.2

**Comment by trob** [comment]
Still not working in 3.4.3 (+Git)

**Comment by cheesegrits** [comment]
I don't see any JS errors, although the behavior is funky.  As this is one of those horribly complex issues, for now "group by is not supported in AJAX" until I get time to work on it.
